name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '10 10 * * 0'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'stable', 'oldstable' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go test -race -covermode=atomic -coverprofile=coverage.txt ./...
      - uses: codecov/codecov-action@v5
